### ISSUE TITLE
Turning the character after placement in the scene causes eratic movements.

### ISSUE THREAD

**Issue by GaryParkin** [ColormaticStudios/quality-godot-first-person-2#11] opened 2024-04-08 13:23 UTC
Steps to reproduce:
Create a new blank scene, add a floor/collision.
Download this controller.
After dragging the character into the scene, grab the character and rotate it on the Y axis like you're attempting to face him/her in a different starting position.
If you press the forward key the character moves sideways.
I would love to hear why.

**Comment by ColormaticStudios** [comment] 2024-04-08 14:00
This was fixed in 11b41ea13dd17c3dba46740c478121c3add5122f, but hasn't made it to a full release yet. It is caused by the movement being based on the rotation of the `Head` node, and not accounting for the rotation of the whole CharacterBody. For now, you can either use the `initial_facing_direction` member variable or download the latest code from GitHub.

**Comment by GaryParkin** [comment] 2024-04-08 14:47
Excellent!  Thank you. I'll add in the new code.  I really like the controller otherwise.

**Closed** 2024-04-09 14:30 UTC
