### ISSUE TITLE
Rotating the main node causes weird behaviour.

### ISSUE THREAD

**Issue by albinaask** [ColormaticStudios/quality-godot-first-person-2#9] opened 2024-03-22 19:36 UTC
When placing the character node into the world, and editing the y rotation property to 180, so the character faces the other way, all the movement controls reverse, if you haven't changed it for 2.4 :)

**Comment by ColormaticStudios** [comment] 2024-03-23 00:01
Duplicate of #5, you can use the `initial_facing_direction` variable to change the rotation. I'm thinking of just making it work with the base rotation though.

**Closed by ColormaticStudios** 2024-03-23 00:01 UTC

**Comment by albinaask** [comment] 2024-03-24 21:54
> Duplicate of #5, you can use the `initial_facing_direction` variable to change the rotation. I'm thinking of just making it work with the base rotation though.

Well I think it would be more in line with the Godot mentality of 'it just works'. Ideally I shouldn't have to read any wiki stuff about how to rotate this node in particular, just rotating it like any other node would do the trick. At least I think that would be the most elegant solution in my opinion. But again. I'm very happy to even just use the addon as it is.

**Comment by ColormaticStudios** [comment] 2024-03-26 03:44
Done (check latest commit)
